<?php

// initialize all variables
$oauthsettings = $this->getExtensionPageUrl('oauthsettings');
$account = $this->getExtensionPageUrl('account');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$support = $this->getExtensionPageUrl('support');
$pricing = $this->getExtensionPageUrl('upgrade');
$activeTab = $this->getCurrentActiveTab();

echo'	<div style=" padding: 0 1%;">
            <div class="topnav" id="myTopnav">
               
                <a class="nav-tab '.($activeTab == 'oauthsettings' ? 'active' : '').'" href="'.$oauthsettings.'">1. OAuth Settings</a>
                <a class="nav-tab '.($activeTab == 'signinsettings' ? 'active' : '').'" href="'.$signinsettings.'">2. Sign In Settings</a>	
                <a class="nav-tab '.($activeTab == 'attrsettings' ? 'active' : '').'" href="'.$attrsettings.'">3. Attribute Mapping</a>	
                <a class="nav-tab '.($activeTab == 'support' ? 'active' : '').'" href="'.$support.'">4. Support / Help</a>
                <a class="nav-tab '.($activeTab == 'upgrade' ? 'active' : '').'" href="'.$pricing.'">5. Upgrade</a>
            </div>
        </div>';
